---
title: "Laboratório 2"
author: "Francesco Giuseppe Carotti"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

```

```{r pacotes}

library(dplyr)
library(readr)
library(lubridate)
library(ggplot2)
library(ggcal)
library(kableExtra)

```


# Estatísticas suficientes

Para a determinação do percentual de voos atrasados na chegadas em mais de 10 minutos, precisamos apenas do número total de voos e do número total de voos que apresentaram este atraso. 

# Obtenção das estatísticas suficientes


```{r}

comp_aereas = c("AA", "DL", "UA", "US")

colunas = cols_only(YEAR = 'i', 
                    MONTH = 'i', 
                    DAY = 'i',
                    ARRIVAL_DELAY = 'i', 
                    AIRLINE = 'c')

get_stats = function(input, pos) {
  
    input %>% 
      filter(!is.na.data.frame(YEAR),
             !is.na.data.frame(MONTH),
             !is.na.data.frame(DAY),
             !is.na.data.frame(ARRIVAL_DELAY),
             !is.na.data.frame(AIRLINE),
             AIRLINE %in% comp_aereas) %>% 
      group_by(DAY, MONTH, YEAR, AIRLINE) %>% 
      summarise(total = n(),
                total_atraso_10 = sum(ARRIVAL_DELAY > 10)) %>% 
      ungroup()
  
}

atrasados = read_csv_chunked("flights-etc.zip", 
                             col_types = colunas,
                             chunk_size = 1e5, 
                             callback = DataFrameCallback$new(get_stats)) 

atrasados %>% 
  kable() %>% 
  kable_styling(bootstrap_options = "striped", 
                full_width = FALSE) %>% 
   scroll_box(width = "100%", 
              height = "400px")

```

# Calculo das estatísticas de interesse

```{r}

compute_stats = function(dados)  {
  
  dados %>% 
    mutate(data = paste(YEAR, MONTH, DAY, 
                        sep = "-") %>% 
                    as_date()) %>% 
    group_by(data, AIRLINE) %>% 
    summarise(perc = sum(total_atraso_10) / sum(total)) %>% 
    ungroup() %>% 
    select(AIRLINE, data, perc)
  
}

atrasados %>% 
  compute_stats() %>% 
  arrange(AIRLINE) %>% 
  kable() %>% 
  kable_styling(bootstrap_options = "striped", 
                full_width = FALSE) %>% 
  scroll_box(width = "100%", 
             height = "400px")

```

# Gráfico

```{r}

pal = scale_fill_gradient(low = "#4575b4",
                          high = "#d73027")

base_calendario = function(stats, cia) {
  
  meio = stats %>% 
          filter(AIRLINE == cia)
  
  ggcal(meio$data, meio$perc) +
    pal
    
}

atrasados %>% 
  compute_stats() %>% 
  base_calendario("AA") +
    ggtitle("Percentual de atrasos na chegada maiores que 10 minutos em cada dia
            no ano de 2015 para a companhia AA")

atrasados %>% 
  compute_stats() %>% 
  base_calendario("DL") +
    ggtitle("Percentual de atrasos na chegada maiores que 10 minutos em cada dia
            no ano de 2015 para a companhia DL")

atrasados %>% 
  compute_stats() %>% 
  base_calendario("UA") +
    ggtitle("Percentual de atrasos na chegada maiores que 10 minutos em cada dia
            no ano de 2015 para a companhia UA")

atrasados %>% 
  compute_stats() %>% 
  base_calendario("US") +
    ggtitle("Percentual de atrasos na chegada maiores que 10 minutos em cada dia
            no ano de 2015 para a companhia US")

```